### ISSUE TITLE
Option for 'state' parameter in configuration

### ISSUE THREAD

**Issue by lemonka** [cosmocode/dokuwiki-plugin-oauthgeneric#6]
hi Cosmocode :)

I believe this plugin is missing option to enable adding state parameter to URL. For some providers this is mandatory - like Authelia. I have no idea how to do this, so I'm doing this forcefully:
```
    /**
     * Check if the given service need to generate a unique state token to build the authorization url.
     *
     * @return bool
     */
    public function needsStateParameterInAuthUrl()
    {
        return true;
        return $this->stateParameterInAuthUrl;
    }
``` 

here: /plugins/oauth/vendor/lusitanian/oauth/src/OAuth/OAuth2/Service

**Comment by 5p4k** [comment]
I am trying to configure Dokuwiki with Authentik, and with the default version of this plugin I get a failure with `OAuth: State not found in session, are you sure you stored it?`. I believe this is the same issue.

I tried the change @lemonka suggested, and it gets past that point. However, our setup has an issue with the reverse proxy which we need to solve, before I can confirm it works.

**Comment by 5p4k** [comment]
Yes, I can confirm, adding that override fixes the issue with Authentik
